### ISSUE TITLE
chore: add husky pre-commit for formatting

### ISSUE THREAD

**Issue by CaseoJKL** [wiktoriavh/ask-good-questions#9]
We could have pre-commit formatting with a certain configuration to avoid different formatting across developers.

---

**Tasks:**

- [x] Default eslint config
- [x] Default prettier config
- [x] husky pre-commit for formatting and linting
- [ ] lint-stage for staged files

**Comment by wiktoriavh** [comment]
I updated your description to include the tasks.
